/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_affichage_utilisateur (void);
GtkWidget* create_ajouter_utiliseur (void);
GtkWidget* create_modifier_utilisateur (void);
GtkWidget* create_gestiondesdonwindow (void);
GtkWidget* create_ajouterdesdonwindow (void);
GtkWidget* create_ConfirmerSuppressionDeDonsWindow (void);
GtkWidget* create_modifierDesDons (void);
GtkWidget* create_accessfichiedonneur (void);
GtkWidget* create_manipfichiedonneur (void);
GtkWidget* create_recherchefichiedonneur (void);
GtkWidget* create_supprimerfichiedonneur (void);
GtkWidget* create_affichagefichedonneur (void);
GtkWidget* create_etablissement (void);
GtkWidget* create_ajouteretablissement (void);
GtkWidget* create_supprimeretablissement (void);
GtkWidget* create_modifieretablissement (void);
GtkWidget* create_afichtrieetablissement (void);
GtkWidget* create_pochesdessangs (void);
GtkWidget* create_login_utilisateur (void);
GtkWidget* create_gestion_rdv (void);
GtkWidget* create_historique_rdv (void);
GtkWidget* create_ajout_rdv (void);
GtkWidget* create_modifier_rdv (void);
GtkWidget* create_choix_admin (void);
