/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *affichage_utilisateur;
  GtkWidget *ajouter_utiliseur;
  GtkWidget *modifier_utilisateur;
  GtkWidget *gestiondesdonwindow;
  GtkWidget *ajouterdesdonwindow;
  GtkWidget *ConfirmerSuppressionDeDonsWindow;
  GtkWidget *modifierDesDons;
  GtkWidget *accessfichiedonneur;
  GtkWidget *manipfichiedonneur;
  GtkWidget *recherchefichiedonneur;
  GtkWidget *supprimerfichiedonneur;
  GtkWidget *affichagefichedonneur;
  GtkWidget *etablissement;
  GtkWidget *ajouteretablissement;
  GtkWidget *supprimeretablissement;
  GtkWidget *modifieretablissement;
  GtkWidget *afichtrieetablissement;
  GtkWidget *pochesdessangs;
  GtkWidget *login_utilisateur;
  GtkWidget *gestion_rdv;
  GtkWidget *historique_rdv;
  GtkWidget *ajout_rdv;
  GtkWidget *modifier_rdv;
  GtkWidget *choix_admin;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  affichage_utilisateur = create_affichage_utilisateur ();
  gtk_widget_show (affichage_utilisateur);
  ajouter_utiliseur = create_ajouter_utiliseur ();
  gtk_widget_show (ajouter_utiliseur);
  modifier_utilisateur = create_modifier_utilisateur ();
  gtk_widget_show (modifier_utilisateur);
  gestiondesdonwindow = create_gestiondesdonwindow ();
  gtk_widget_show (gestiondesdonwindow);
  ajouterdesdonwindow = create_ajouterdesdonwindow ();
  gtk_widget_show (ajouterdesdonwindow);
  ConfirmerSuppressionDeDonsWindow = create_ConfirmerSuppressionDeDonsWindow ();
  gtk_widget_show (ConfirmerSuppressionDeDonsWindow);
  modifierDesDons = create_modifierDesDons ();
  gtk_widget_show (modifierDesDons);
  accessfichiedonneur = create_accessfichiedonneur ();
  gtk_widget_show (accessfichiedonneur);
  manipfichiedonneur = create_manipfichiedonneur ();
  gtk_widget_show (manipfichiedonneur);
  recherchefichiedonneur = create_recherchefichiedonneur ();
  gtk_widget_show (recherchefichiedonneur);
  supprimerfichiedonneur = create_supprimerfichiedonneur ();
  gtk_widget_show (supprimerfichiedonneur);
  affichagefichedonneur = create_affichagefichedonneur ();
  gtk_widget_show (affichagefichedonneur);
  etablissement = create_etablissement ();
  gtk_widget_show (etablissement);
  ajouteretablissement = create_ajouteretablissement ();
  gtk_widget_show (ajouteretablissement);
  supprimeretablissement = create_supprimeretablissement ();
  gtk_widget_show (supprimeretablissement);
  modifieretablissement = create_modifieretablissement ();
  gtk_widget_show (modifieretablissement);
  afichtrieetablissement = create_afichtrieetablissement ();
  gtk_widget_show (afichtrieetablissement);
  pochesdessangs = create_pochesdessangs ();
  gtk_widget_show (pochesdessangs);
  login_utilisateur = create_login_utilisateur ();
  gtk_widget_show (login_utilisateur);
  gestion_rdv = create_gestion_rdv ();
  gtk_widget_show (gestion_rdv);
  historique_rdv = create_historique_rdv ();
  gtk_widget_show (historique_rdv);
  ajout_rdv = create_ajout_rdv ();
  gtk_widget_show (ajout_rdv);
  modifier_rdv = create_modifier_rdv ();
  gtk_widget_show (modifier_rdv);
  choix_admin = create_choix_admin ();
  gtk_widget_show (choix_admin);

  gtk_main ();
  return 0;
}

